# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"unhex": "defaults.ipynb",
         "unimplemented": "defaults.ipynb",
         "list_to_indexdir": "factory.ipynb",
         "create_model": "factory.ipynb",
         "assemble_sunspec_model": "factory.ipynb",
         "assemble": "factory.ipynb",
         "ShadowSunspecEncoder": "factory.ipynb",
         "NAMESPACE": "factory.ipynb",
         "encode": "factory.ipynb",
         "ExampleValue": "values.ipynb",
         "ExampleValues": "values.ipynb",
         "get_point_value": "values.ipynb",
         "ShadowSunspecValueEncoder": "values.ipynb",
         "example_device": "values.ipynb",
         "ev": "values.ipynb",
         "example_values": "values.ipynb",
         "READONLY": "factory.ipynb",
         "WRITEABLE": "factory.ipynb",
         "GeneralSunspecEncoder": "factory.ipynb",
         "TelemetrySunspecEncoder": "factory.ipynb"}

modules = ["defaults.py",
           "factory.py",
           "values.py"]

doc_url = "https://WilliamG.github.io/shadowsunspec/"

git_url = "https://github.com/WilliamG/shadowsunspec/tree/master/"

def custom_doc_links(name): return None
