# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/defaults.ipynb (unless otherwise specified).

__all__ = ['unhex', 'unimplemented']

# Cell
from sunspec.core.suns import *
def unhex(hexstr:str):
    return int(hexstr, 16)
unimplemented = {}

# Cell
unimplemented[SUNS_TYPE_INT16]=SUNS_UNIMPL_INT16
unimplemented[SUNS_TYPE_UINT16] = SUNS_UNIMPL_UINT16
unimplemented[SUNS_TYPE_ACC16]= SUNS_UNIMPL_ACC16
unimplemented[SUNS_TYPE_ENUM16] = SUNS_UNIMPL_ENUM16
unimplemented[SUNS_TYPE_BITFIELD16] = SUNS_UNIMPL_BITFIELD16
unimplemented[SUNS_TYPE_PAD] = unhex('0x8000')

# Cell
unimplemented[SUNS_TYPE_INT32] = SUNS_UNIMPL_INT32
unimplemented[SUNS_TYPE_UINT32] = SUNS_UNIMPL_UINT32
unimplemented[SUNS_TYPE_ACC32] = SUNS_UNIMPL_ACC32
unimplemented[SUNS_TYPE_ENUM32] = SUNS_UNIMPL_ENUM32
unimplemented[SUNS_TYPE_BITFIELD32] = SUNS_UNIMPL_BITFIELD32
unimplemented[SUNS_TYPE_IPADDR] = SUNS_UNIMPL_IPADDR

# Cell
unimplemented[SUNS_TYPE_INT64] = SUNS_UNIMPL_INT64
unimplemented[SUNS_TYPE_UINT64] = SUNS_UNIMPL_UINT64
unimplemented[SUNS_TYPE_ACC64] =SUNS_UNIMPL_ACC64

# Cell
unimplemented[SUNS_TYPE_IPV6ADDR] =SUNS_UNIMPL_IPV6ADDR

# Cell
unimplemented[SUNS_TYPE_STRING] = SUNS_UNIMPL_STRING

# Cell
unimplemented[SUNS_TYPE_FLOAT32] = SUNS_UNIMPL_FLOAT32

# Cell
unimplemented['float64'] = unhex('0x7FF8000000000000')

# Cell
unimplemented[SUNS_TYPE_SUNSSF] = SUNS_UNIMPL_SUNSSF